const schools = [
  {
    id: "GVPS",
    name: "Green Valley Primary School",
    short: "Green Valley PS",
    enrolled: 210,
    present: 198,
    meals: 195,
    menu: 100,
    photos: 95,
    nutrition: 92,
    status: "On Track",
    calories: 562,
    waste: 7,
  },
  {
    id: "SPS",
    name: "Sunrise Primary School",
    short: "Sunrise PS",
    enrolled: 185,
    present: 172,
    meals: 170,
    menu: 90,
    photos: 92,
    nutrition: 91,
    status: "On Track",
    calories: 548,
    waste: 6,
  },
  {
    id: "RPS",
    name: "Riverdale Primary School",
    short: "Riverdale PS",
    enrolled: 160,
    present: 150,
    meals: 148,
    menu: 100,
    photos: 88,
    nutrition: 88,
    status: "On Track",
    calories: 510,
    waste: 9,
  },
  {
    id: "LPS",
    name: "Lotus Primary School",
    short: "Lotus PS",
    enrolled: 220,
    present: 205,
    meals: 198,
    menu: 80,
    photos: 85,
    nutrition: 82,
    status: "Watch",
    calories: 472,
    waste: 13,
  },
  {
    id: "NPS",
    name: "Nehru Primary School",
    short: "Nehru PS",
    enrolled: 175,
    present: 162,
    meals: 150,
    menu: 70,
    photos: 90,
    nutrition: 80,
    status: "Alert",
    calories: 468,
    waste: 15,
  },
  {
    id: "SHPS",
    name: "Shanti Primary School",
    short: "Shanti PS",
    enrolled: 190,
    present: 178,
    meals: 175,
    menu: 100,
    photos: 93,
    nutrition: 94,
    status: "On Track",
    calories: 560,
    waste: 5,
  },
  {
    id: "APS",
    name: "Aastha Primary School",
    short: "Aastha PS",
    enrolled: 200,
    present: 185,
    meals: 180,
    menu: 90,
    photos: 91,
    nutrition: 93,
    status: "On Track",
    calories: 555,
    waste: 6,
  },
  {
    id: "PPS",
    name: "Pragati Primary School",
    short: "Pragati PS",
    enrolled: 180,
    present: 168,
    meals: 165,
    menu: 90,
    photos: 89,
    nutrition: 90,
    status: "On Track",
    calories: 520,
    waste: 8,
  },
  {
    id: "UPS",
    name: "Udaan Primary School",
    short: "Udaan PS",
    enrolled: 170,
    present: 155,
    meals: 150,
    menu: 80,
    photos: 94,
    nutrition: 86,
    status: "Watch",
    calories: 498,
    waste: 11,
  },
  {
    id: "NDPS",
    name: "Nayi Disha Primary School",
    short: "Nayi Disha PS",
    enrolled: 172,
    present: 169,
    meals: 167,
    menu: 100,
    photos: 96,
    nutrition: 95,
    status: "On Track",
    calories: 545,
    waste: 4,
  },
];

const imagesFor = (s) => ({
  stock: `images/${s.id.toLowerCase().replace("gvps", "green_valley_ps").replace("sps", "sunrise_ps").replace("rps", "riverdale_ps").replace("lps", "lotus_ps").replace("nps", "nehru_ps").replace("shps", "shanti_ps").replace("aps", "aastha_ps").replace("pps", "pragati_ps").replace("ups", "udaan_ps").replace("ndps", "nayi_disha_ps")}_stock.jpg`,
  cooking: `images/${s.id.toLowerCase().replace("gvps", "green_valley_ps").replace("sps", "sunrise_ps").replace("rps", "riverdale_ps").replace("lps", "lotus_ps").replace("nps", "nehru_ps").replace("shps", "shanti_ps").replace("aps", "aastha_ps").replace("pps", "pragati_ps").replace("ups", "udaan_ps").replace("ndps", "nayi_disha_ps")}_cooking.jpg`,
  serving: `images/${s.id.toLowerCase().replace("gvps", "green_valley_ps").replace("sps", "sunrise_ps").replace("rps", "riverdale_ps").replace("lps", "lotus_ps").replace("nps", "nehru_ps").replace("shps", "shanti_ps").replace("aps", "aastha_ps").replace("pps", "pragati_ps").replace("ups", "udaan_ps").replace("ndps", "nayi_disha_ps")}_serving.jpg`,
  before: `images/${s.id.toLowerCase().replace("gvps", "green_valley_ps").replace("sps", "sunrise_ps").replace("rps", "riverdale_ps").replace("lps", "lotus_ps").replace("nps", "nehru_ps").replace("shps", "shanti_ps").replace("aps", "aastha_ps").replace("pps", "pragati_ps").replace("ups", "udaan_ps").replace("ndps", "nayi_disha_ps")}_plate_before.jpg`,
  after: `images/${s.id.toLowerCase().replace("gvps", "green_valley_ps").replace("sps", "sunrise_ps").replace("rps", "riverdale_ps").replace("lps", "lotus_ps").replace("nps", "nehru_ps").replace("shps", "shanti_ps").replace("aps", "aastha_ps").replace("pps", "pragati_ps").replace("ups", "udaan_ps").replace("ndps", "nayi_disha_ps")}_plate_after.jpg`,
});

const mealItems = [
  {
    item: "Roti (wheat)",
    qty: "1 piece (52 g)",
    measure: "Diameter 16.5 cm • Thickness 2.1 mm",
    kcal: 167,
    protein: 5.4,
    iron: 1.8,
    conf: 92,
  },
  {
    item: "Dal (toor)",
    qty: "108 ml (~25 g raw)",
    measure: "Consistency: Normal • Dilution: No",
    kcal: 86,
    protein: 5.6,
    iron: 1.2,
    conf: 88,
  },
  {
    item: "Rice (cooked)",
    qty: "180 g",
    measure: "Grain type: Medium • Moisture: Normal",
    kcal: 234,
    protein: 4.8,
    iron: 0.4,
    conf: 90,
  },
  {
    item: "Mixed Sabzi",
    qty: "75 g",
    measure: "Potato, beans, carrot detected",
    kcal: 62,
    protein: 1.5,
    iron: 0.9,
    conf: 85,
  },
];

const attendance = [
  1670, 1692, 1708, 1684, 1719, 1741, 1734, 1760, 1748, 1755, 1739, 1768, 1772,
  1759, 1745, 1764, 1780, 1773, 1768, 1784, 1770, 1792, 1781, 1776, 1790, 1785,
  1798, 1794,
];
const mealsServed = [
  1622, 1640, 1658, 1639, 1675, 1691, 1684, 1704, 1690, 1701, 1689, 1715, 1718,
  1708, 1695, 1711, 1727, 1719, 1710, 1731, 1717, 1739, 1728, 1722, 1735, 1730,
  1743, 1738,
];

const alerts = [
  {
    level: "High",
    school: "Nehru PS",
    title: "Meals served below attendance",
    detail: "150 meals for 162 children present",
    time: "Today 11:48",
  },
  {
    level: "High",
    school: "Lotus PS",
    title: "Menu deviation detected",
    detail: "Dal + rice served; vegetable item missing",
    time: "Today 12:02",
  },
  {
    level: "Medium",
    school: "Udaan PS",
    title: "Plate photo completion low",
    detail: "94% today; previous target 95%",
    time: "Yesterday",
  },
  {
    level: "Medium",
    school: "Sunrise PS",
    title: "Stock consumption variance",
    detail: "Vegetable usage -8% vs expected",
    time: "Yesterday",
  },
  {
    level: "Info",
    school: "Green Valley PS",
    title: "AI analysis complete",
    detail: "195 plates processed at 92% adequacy",
    time: "Today 13:05",
  },
];
